// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Smart_Event_Management_and_Ticketing_System.Data;

#nullable disable

namespace Smart_Event_Management_and_Ticketing_System.Migrations
{
    [DbContext(typeof(EventSystemContext))]
    [Migration("20260202063019_InitialProjectSetup")]
    partial class InitialProjectSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BOOKING_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("EventId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EVENT_ID");

                    b.Property<int>("MemberId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SEATTYPE");

                    b.HasKey("BookingId");

                    b.HasIndex("EventId");

                    b.HasIndex("MemberId");

                    b.ToTable("BOOKING");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EVENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("AVAILABILITY");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EVENTDATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EVENTNAME");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VENUE");

                    b.HasKey("Id");

                    b.ToTable("EVENT");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FULLNAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("MemberId");

                    b.ToTable("MEMBER");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REVIEW_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("COMMENTS");

                    b.Property<int>("EventId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EVENT_ID");

                    b.Property<int>("MemberId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBER_ID");

                    b.HasKey("ReviewId");

                    b.HasIndex("EventId");

                    b.HasIndex("MemberId");

                    b.ToTable("REVIEW");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Booking", b =>
                {
                    b.HasOne("Smart_Event_Management_and_Ticketing_System.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Event_Management_and_Ticketing_System.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Review", b =>
                {
                    b.HasOne("Smart_Event_Management_and_Ticketing_System.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Event_Management_and_Ticketing_System.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
